caches/urls.py
from django.urls import path

from . import views


app_name = 'caches'

urlpatterns = [
    path('', views.CacheListView.as_view(), name='cacheList'),
    path('<int:pk>/', views.CacheDetailView.as_view(), name='cacheDetail'),
    path('add/', views.CacheCreateView.as_view(), name='cacheCreate'),

    path('<int:pk>/add', views.ReactionCreateView.as_view(), name='reactionCreate'),
]

open_caching/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('caches.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
]

caches/models.py
from django.db import models
from django.conf import settings
from django.utils.timezone import now
from django.urls import reverse

from caches.fields import LocationField


class Cache(models.Model):
    'Cache model'

    title = models.CharField(max_length=50)
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    nb_times_found = models.IntegerField(default=0)
    nb_times_not_found = models.IntegerField(default=0)
    description = models.CharField(max_length=250)
    creation_date = models.DateTimeField(default=now)
    location = LocationField()

    def __str__(self):
        return str(self.title)

    def get_absolute_url(self):
        'get absolute url'
        return reverse('caches:cacheDetail', kwargs={'pk': self.pk})


class Reaction(models.Model):
    'Reaction model'

    target = models.ForeignKey(Cache, on_delete=models.CASCADE)
    found = models.BooleanField()
    comment = models.CharField(max_length=250)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    creation_date = models.DateTimeField(default=now)

    def __str__(self):
        return str(self.comment)[:30]

    def get_absolute_url(self):
        'get absolute url'
        return reverse('caches:cacheDetail', kwargs={'pk': self.target.id})

caches/forms.py
from django.forms import ModelForm, HiddenInput

from .models import Cache, Reaction


class CacheCreateForm(ModelForm):
    'Form used to create a cache.'

    class Meta:
        model = Cache
        fields = ['title', 'description', 'location']
        widgets = {
            'location': HiddenInput()
        }


class ReactionCreateForm(ModelForm):
    'A form used to add a reaction to a cache.'

    class Meta:
        model = Reaction
        fields = ['found', 'comment']

caches/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import CacheCreateForm, ReactionCreateForm
from .models import Cache, Reaction


class CacheListView(ListView):
    'View to list caches'
    def get_queryset(self):
        return Cache.objects.order_by('-creation_date')[:50]


class CacheDetailView(LoginRequiredMixin, DetailView):
    'View to show cache detail'
    model = Cache


class CacheCreateView(LoginRequiredMixin, CreateView):
    'View to add a cache'

    model = Cache
    form_class = CacheCreateForm

    def form_valid(self, form):
        form.instance.creator = self.request.user
        return super().form_valid(form)


class ReactionCreateView(LoginRequiredMixin, CreateView):
    'View to add a reaction to a cache'

    model = Reaction
    form_class = ReactionCreateForm

    def form_valid(self, form):
        print('\n\n=== pk =', self.kwargs['pk'], ' ===\n\n')
        form.instance.author = self.request.user
        form.instance.target = Cache.objects.get(pk=self.kwargs['pk'])
        form.instance.found = 'found' in self.request.POST
        self.update_counter(form.instance.found, form.instance.target)
        return super().form_valid(form)

    def update_counter(self, is_found: bool, target):
        '''Increment the correct target counter, wich is:
        `nb_times_found` if the cache has been marked as found in the reaction,
        or `nb_times_not_found` otherwise.'''

        if is_found:
            target.nb_times_found += 1
        else:
            target.nb_times_not_found += 1
        target.save()

caches/templates/caches/cache_detail.html
{% extends "base.html" %}

{% block title %}{{ cache.title }}{% endblock %}
{% block content %}

<h2>Cache details</h2>

<a id="cache-list-link" href="{% url 'caches:cacheList' %}">Return to caches list</a>

<div id="cache-info" data-loc="{{ cache.location }}" data-title="{{ cache.title }}">
	<ul>
		<li>Title: {{ cache.title }}</li>
		<li>Description: {{ cache.description }}</li>
		<li>Created at: {{ cache.creation_date }} times.</li>
		<li>Found: {{ cache.nb_times_found }}</li>
		<li>Not found: {{ cache.nb_times_not_found }}</li>
	</ul>
</div>

<div class="leaflet-container" id="map-cache-detail"></div>

{% if cache.reaction_set.all %}
	<p>Reactions:</p>
	<ul>
		{% for reaction in cache.reaction_set.all %}
			<li>
				{{ reaction.found | yesno:"✔,✘" }}
				{{ reaction.creation_date }} :
				<b>{{ reaction.comment }}</b>
			</li>
		{% endfor %}
	</ul>
{% else %}
	<p>No reactions yet.</p>
{% endif %}

<p>Add reaction:</p>
<form action="{% url 'caches:reactionCreate' cache.id %}" method="post">
	{% csrf_token %}
	Found <input type="checkbox" name="found" checked>
	Comment <input name="comment">
	<input class="pure-button" type="submit" value="Send">
</form>

{% endblock %}

caches/templates/caches/cache_form.html
{% extends "base.html" %}

{% block title %}Add a cache{% endblock %}
{% block content %}

<h2>Add a new cache</h2>

<div class="leaflet-container" id="map-add-cache"></div>

<form action="{% url 'caches:cacheCreate' %}" method="post">
	{% csrf_token %}
	{{ form }}
	<input id="add-cache" class="pure-button" type="submit" value="Add cache">
</form>

{% endblock %}

caches/templates/caches/cache_list.html
{% extends "base.html" %}

{% block title %}Cache list{% endblock %}
{% block content %}

<h2>List of caches</h2>

<div id="caches-info">
	<div class="leaflet-container" id="map-cache-list"></div>

	{% if cache_list %}
	<ul id="cache-list">
		{% for cache in cache_list %}
		<li data-loc="{{ cache.location }}" data-id="{{ cache.id }}" data-title="{{ cache.title }}">
			<a href="{% url 'caches:cacheDetail' cache.id %}">{{ cache.title }}</a>
		</li>
		{% endfor %}
	</ul>
	{% else %}
	<p>No caches available.</p>
	{% endif %}
</div>

{% if user.is_authenticated %}
	<a class="pure-button" href="{% url 'caches:cacheCreate' %}">Add cache</a>
{% endif %}

{% endblock %}

open_caching/templates/base.html
<!DOCTYPE html>
<html>
	{% include "head.html" %}
	<body>
		{% include "header.html" %}
		<main>
			{% block content %}
			{% endblock %}
		</main>
	</body>
</html>

open_caching/templates/head.html
{% load static %}

<head>
	<meta charset="utf-8">
	<title>{% block title %}{% endblock %} | OpenCaching</title>
	<link rel="icon" type="image/png" href="{% static 'logo_64.png' %}">

	<link rel="stylesheet" href="{% static 'caches/vendor/purecss/pure-min.css' %}">
	<link rel="stylesheet" href="{% static 'caches/vendor/leaflet/leaflet.css' %}">
	<link rel="stylesheet" href="{% static 'website.css' %}">
	<link rel="stylesheet" href="{% static 'caches/cache.css' %}">

	<script src="{% static 'caches/vendor/leaflet/leaflet.js' %}" type="text/javascript"></script>
	<script src="{% static 'caches/map.js' %}" type="text/javascript"></script>
</head>

open_caching/templates/header.html
<header>
	<h1><a href="/">OpenCaching</a></h1>
	{% if user.is_authenticated %}
		<p>Logged as <b>{{ user.username }}</b> | <a href="{% url 'logout' %}">Logout</a></p>
	{% else %}
		<p><a href="{% url 'login' %}">Log in</a></p>
	{% endif %}
</header>